# Generated by Django 5.1 on 2024-09-04 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_gestion_de_autos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='sistema_gestion_de_autos.vehiculo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='sistema_gestion_de_autos.propietario'),
        ),
    ]
